run:
	gcc dir_handler.c main.c file_handler.c -o main
	mkdir "mydirname"
	@echo "Hi my name is Sasha" > ./mydirname/helloworld
	@echo "Os is really nice" > ./mydirname/helloworld
	@echo "it is really cold outside today" > ./mydirname/today
	./main ./mydirname